### PR TITLE
Updates package structure

### PR DESCRIPTION
**Pull request by moonso**
Hi, I've made a package of the project. Nice job @bjhall , the code is well written and easy to understand! There are some things I would like to update but it's better to keep down the size of the PRs. 

Here is a summary of what was done in this PR:

- created a installable python package with setup.py etc
- split some of the functions into different files 
- updated CLI to use click, hope that's fine with you
- changed `get_UPD_informative_sites` to return a generator to reduce memory use
- updated docstrings

So some other stuff I would like to add when this is merged:

- Add tests to most of the functions
- `call_regions` should also return a generator
- Skip dependency of cyvcf2 if not to cumbersome (for installation reasons)
- Check with some different dummy VCFs if upd behaves as expected

### CODE REVIEW

**Review by dnil — APPROVED** [review]
Looks good to me, but I feel Björn should merge this one as the Copyright / License is updated!

**Review by bjhall — CHANGES_REQUESTED** [review]
I fixed some minor syntax errors, but there is one more outstanding issue which I'm uncertain how to fix the "right" way.

Since `get_UPD_informative_sites` now returns an iterator which is consumed by `call_regions`, the iterator is already exhausted when `output_informative_sites` is called, resulting in an empty output file.

Some quick googling indicates that itertools.tee may be the way to go?

**Comment by moonso** [comment]
Aha @bjhall , I thought that it was only consumed once in `call_regions` and that `output_informative_sites` used the output from `call_regions`. I'll fix that

**Comment by moonso** [comment]
Hi @bjhall , so I have done what we discussed. The interface has changed a bit so will update README. I've changed so that the AF annotation not necessarily have to be done by VEP. Please have a look when you have time

**Comment by moonso** [comment]
It works well with python3

**Comment by bjhall** [comment]
Looks and works great! Thanks a lot for your efforts. I'll merge.

**Pull request merged**
